/**
 * Expo config plugin that wires up a release signing config for Android.
 *
 * The native `android/` project is generated by `expo prebuild` and is not
 * committed, so the release keystore cannot be configured by hand. This plugin
 * patches the generated `android/app/build.gradle` so that release builds are
 * signed with a keystore supplied through Gradle properties:
 *
 *   TREELY_UPLOAD_STORE_FILE
 *   TREELY_UPLOAD_STORE_PASSWORD
 *   TREELY_UPLOAD_KEY_ALIAS
 *   TREELY_UPLOAD_KEY_PASSWORD
 *
 * These are provided by CI (see .github/workflows/frontend-release.yml). When
 * the properties are absent (e.g. local debug builds) the release config is
 * simply left unconfigured and Gradle keeps using the debug keystore, so this
 * plugin is a no-op for everyday development.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('TREELY_UPLOAD_STORE_FILE')) {
                storeFile file(TREELY_UPLOAD_STORE_FILE)
                storePassword TREELY_UPLOAD_STORE_PASSWORD
                keyAlias TREELY_UPLOAD_KEY_ALIAS
                keyPassword TREELY_UPLOAD_KEY_PASSWORD
            }
        }`;

function addReleaseSigningConfig(contents) {
  if (contents.includes('TREELY_UPLOAD_STORE_FILE')) {
    return contents;
  }

  // Point the release build type at the (to-be-added) release signing config.
  // Done first, while `signingConfigs` only contains `debug`, so the only
  // `release {` block in the file is the build type we want to target.
  const buildTypeAnchor = /release \{\n([\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!buildTypeAnchor.test(contents)) {
    throw new Error(
      'withAndroidSigning: could not find the release build type in build.gradle',
    );
  }
  contents = contents.replace(
    buildTypeAnchor,
    'release {\n$1signingConfig signingConfigs.release',
  );

  // Insert a `release` signing config right after the existing `debug` one.
  const signingConfigsAnchor = /signingConfigs \{\n(\s*)debug \{[\s\S]*?\n\1\}/;
  const match = contents.match(signingConfigsAnchor);
  if (!match) {
    throw new Error(
      'withAndroidSigning: could not find the signingConfigs.debug block in build.gradle',
    );
  }
  contents = contents.replace(
    signingConfigsAnchor,
    `${match[0]}\n${RELEASE_SIGNING_CONFIG}`,
  );

  return contents;
}

module.exports = function withAndroidSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withAndroidSigning: expected a groovy build.gradle, got ' +
          cfg.modResults.language,
      );
    }
    cfg.modResults.contents = addReleaseSigningConfig(cfg.modResults.contents);
    return cfg;
  });
};
