/**
 * Expo config plugin that sources the Android `versionCode` from the
 * ANDROID_VERSION_CODE environment variable.
 *
 * The native `android/` project is generated by `expo prebuild`, so the
 * version code baked into `android/app/build.gradle` comes from the app config.
 * Without this, every build ships `versionCode 1` and Android refuses to
 * install a build over an existing one with the same code (and the Play Store
 * rejects re-uploads).
 *
 * CI passes the workflow run number (see .github/workflows/frontend-release.yml),
 * which is monotonically increasing. When the variable is unset — the normal
 * case for local development — the value from app.json is kept.
 */
module.exports = function withAndroidVersionCode(config) {
  const raw = process.env.ANDROID_VERSION_CODE;

  if (!raw) {
    return config;
  }

  const versionCode = Number(raw);
  if (!Number.isInteger(versionCode) || versionCode < 1) {
    throw new Error(
      `withAndroidVersionCode: ANDROID_VERSION_CODE must be a positive integer, got "${raw}"`,
    );
  }

  return {
    ...config,
    android: {
      ...config.android,
      versionCode,
    },
  };
};
